name: Test KiBot reusable workflow - Board Change

on:
  # Manually trigger workflow
  workflow_dispatch:

  # Trigger when board is edited
  push:
    branches: main
    paths:
      - "**.kicad_pcb"

jobs:
  Board_change:
    uses: AntarktisZ11/reusable-workflows/.github/workflows/kicad_board_change.yaml@main
    with:
      KiCadProjectName: ESP32-CAM-WebServer-Circuit
      KiCadProjectDir: pcb
