name: Test KiBot reusable workflow - Board Change

on:
  workflow_dispatch:
  
jobs:
  Board_change:
    uses: AntarktisZ11/reusable-workflows/.github/workflows/kicad_board_change.yaml@main
    with:
      KiCadProjectName: ESP32-CAM-WebServer-Circuit
      KiCadProjectDir: pcb
