name: Test KiBot reusable workflow - Schematic Change

on:
  workflow_dispatch:
  
jobs:
  Schematic_change:
    uses: AntarktisZ11/reusable-workflows/.github/workflows/kicad_schematic_change.yaml@main
    with:
      BaseFileName: ESP32-CAM-WebServer-Circuit
      KiCadProjectDir: pcb
