name: Test KiBot reusable workflow - Schematic Change

on:
  # Manually trigger workflow
  workflow_dispatch:
    inputs:
      KiBot-Verbosity:
        description: "Log levels for KiBot"
        required: false
        default: "0"
        type: choice
        options:
          - "0"
          - "1"
          - "2"
          - "3"

  # Trigger when schematic is edited
  push:
    branches: main
    paths:
      - "**.kicad_sch"

jobs:
  Schematic_change:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    uses: AntarktisZ11/reusable-workflows/.github/workflows/kicad_schematic_change.yaml@main
    with:
      KiCadProjectName: ESP32-CAM-WebServer-Circuit
      KiCadProjectDir: pcb
      KiBot-Verbosity: ${{ inputs.KiBot-Verbosity || '0' }}
