name: Test KiBot reusable workflow - Output all

on:
  workflow_dispatch:
  
jobs:
  Output_all_KiBot:
    uses: AntarktisZ11/reusable-workflows/.github/workflows/kicad_test_all.yaml@main
    with:
      KiCadProjectName: ESP32-CAM-WebServer-Circuit
      KiCadProjectDir: pcb
